blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/incendiosoftware/Barnaby/security/advisories/new
    about: Report security vulnerabilities privately.
